"""empty message

Revision ID: 11b21ed4579d
Revises: b4630010d4fa
Create Date: 2019-07-28 23:12:34.638172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b21ed4579d'
down_revision = 'b4630010d4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuisine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuisine_name'), 'cuisine', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cuisine_name'), table_name='cuisine')
    op.drop_table('cuisine')
    # ### end Alembic commands ###
