"""empty message

Revision ID: 1a69c976acca
Revises: 74fa9864506e
Create Date: 2019-09-22 16:54:14.818710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a69c976acca'
down_revision = '74fa9864506e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment', sa.String(length=500), nullable=True))
    op.add_column('comment', sa.Column('website', sa.String(length=64), nullable=True))
    op.drop_index('ix_comment_name', table_name='comment')
    op.create_index(op.f('ix_comment_name'), 'comment', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_name'), table_name='comment')
    op.create_index('ix_comment_name', 'comment', ['name'], unique=1)
    op.drop_column('comment', 'website')
    op.drop_column('comment', 'comment')
    # ### end Alembic commands ###
