"""empty message

Revision ID: 48390ce54d6d
Revises: d939d32ac177
Create Date: 2019-08-11 14:35:20.280830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48390ce54d6d'
down_revision = 'd939d32ac177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_allergens',
    sa.Column('allergen_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergen.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], )
    )
    op.create_table('_ingredients',
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], )
    )
    op.drop_table('ingredients')
    op.add_column('recipe', sa.Column('image', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'image')
    op.create_table('ingredients',
    sa.Column('ingredient_id', sa.INTEGER(), nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], )
    )
    op.drop_table('_ingredients')
    op.drop_table('_allergens')
    # ### end Alembic commands ###
