"""empty message

Revision ID: 6381ed3ba7c7
Revises: 48390ce54d6d
Create Date: 2019-08-11 19:09:31.860279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6381ed3ba7c7'
down_revision = '48390ce54d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('cooking_time', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('serves_num_people', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('time_to_prepare', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'time_to_prepare')
    op.drop_column('recipe', 'serves_num_people')
    op.drop_column('recipe', 'cooking_time')
    # ### end Alembic commands ###
