"""empty message

Revision ID: 6e94f7c8554f
Revises: cdf9d3cf110d
Create Date: 2019-09-22 19:54:06.292623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e94f7c8554f'
down_revision = 'cdf9d3cf110d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nutrition_facts')
    op.add_column('comment', sa.Column('email', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'email')
    op.create_table('nutrition_facts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('calories', sa.INTEGER(), nullable=True),
    sa.Column('carbohydrates', sa.INTEGER(), nullable=True),
    sa.Column('proteins', sa.INTEGER(), nullable=True),
    sa.Column('fats', sa.INTEGER(), nullable=True),
    sa.Column('cholesterol', sa.INTEGER(), nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
