"""empty message

Revision ID: bda17831bb2c
Revises: 6e94f7c8554f
Create Date: 2019-09-22 20:00:31.292359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda17831bb2c'
down_revision = '6e94f7c8554f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comment_name', table_name='comment')
    op.drop_index('ix_comment_timestamp', table_name='comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_comment_timestamp', 'comment', ['timestamp'], unique=False)
    op.create_index('ix_comment_name', 'comment', ['name'], unique=False)
    # ### end Alembic commands ###
