"""empty message

Revision ID: d0a9d553ee54
Revises: ecfec4bc0255
Create Date: 2019-10-06 20:26:58.886240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a9d553ee54'
down_revision = 'ecfec4bc0255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('short_description', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'short_description')
    # ### end Alembic commands ###
