"""empty message

Revision ID: f6e21c741f6a
Revises: 1061c6e3f439
Create Date: 2019-08-31 12:20:35.060853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e21c741f6a'
down_revision = '1061c6e3f439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('calories', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('carbohydrates', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('cholesterol', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('fats', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('proteins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'proteins')
    op.drop_column('recipe', 'fats')
    op.drop_column('recipe', 'cholesterol')
    op.drop_column('recipe', 'carbohydrates')
    op.drop_column('recipe', 'calories')
    # ### end Alembic commands ###
